"""initial vnp schema

Revision ID: 145939825773
Revises: 
Create Date: 2026-07-13 03:14:25.994308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '145939825773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vnp_alert_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_api', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('provider', 'customer', 'validator', 'operator', name='tenant_type_enum'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_scope_time', 'vnp_audit_logs', ['scope_type', 'scope_id', 'created_at'], unique=False)
    op.create_table('vnp_claim_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.String(length=200), nullable=False),
    sa.Column('api_domain', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=False),
    sa.Column('dns_record', sa.String(length=255), nullable=False),
    sa.Column('dns_value', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vnp_claim_requests_api_id'), 'vnp_claim_requests', ['api_id'], unique=False)
    op.create_table('vnp_claimed_apis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=False),
    sa.Column('claim_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score_low_alert', sa.Boolean(), nullable=False),
    sa.Column('score_low_threshold', sa.Integer(), nullable=False),
    sa.Column('last_score_alert_sent', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vnp_claimed_apis_api_id'), 'vnp_claimed_apis', ['api_id'], unique=True)
    op.create_table('vnp_customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('billing_mode', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('open', 'acknowledged', 'resolved', 'suppressed', name='incident_state_enum'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_state_opened', 'vnp_incidents', ['state', 'opened_at'], unique=False)
    op.create_table('vnp_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('vnp_validators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('stake_amount', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('operator_entity', sa.String(length=255), nullable=True),
    sa.Column('stake_currency', sa.String(length=3), nullable=True),
    sa.Column('stake_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.Enum('active', 'suspended', 'challenged', 'retired', name='validator_state_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vnp_apis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('api_did', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('health_path', sa.String(), nullable=False),
    sa.Column('auth_scheme', sa.String(length=50), nullable=False),
    sa.Column('x402_ready', sa.Boolean(), nullable=False),
    sa.Column('pricing_model', sa.String(length=50), nullable=False),
    sa.Column('current_composite_score', sa.Float(), nullable=False),
    sa.Column('stability_rating', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'degraded', 'disabled', 'pending', name='api_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['vnp_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_did')
    )
    op.create_table('vnp_attestations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validator_id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Enum('proposed', 'accepted', 'rejected', name='attestation_state_enum'), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['validator_id'], ['vnp_validators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_prepaid_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('available_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('reserved_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'currency', name='uq_vnp_prepaid_balances_cust_cur')
    )
    op.create_table('vnp_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'name', 'environment', name='uq_vnp_projects_cust_name_env')
    )
    op.create_table('vnp_route_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_p99_latency_ms', sa.Integer(), nullable=True),
    sa.Column('minimum_trust_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('allowed_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_provider_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failover_mode', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_api_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id', 'region_code', name='uq_vnp_api_regions_api_region')
    )
    op.create_index('idx_api_regions_lookup', 'vnp_api_regions', ['api_id', 'region_code'], unique=False, postgresql_where=sa.text('active = true'))
    op.create_table('vnp_probe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('partition_key', sa.String(length=20), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('worker_signature', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('http_version', sa.String(length=10), nullable=True),
    sa.Column('tls_version', sa.String(length=20), nullable=True),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_hash', sa.String(), nullable=True),
    sa.Column('provenance_hash', sa.String(), nullable=True),
    sa.Column('cryptography_anchor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_probe_events_api_region_time', 'vnp_probe_events', ['api_id', 'region', 'measured_at'], unique=False)
    op.create_index(op.f('ix_vnp_probe_events_measured_at'), 'vnp_probe_events', ['measured_at'], unique=False)
    op.create_index(op.f('ix_vnp_probe_events_partition_key'), 'vnp_probe_events', ['partition_key'], unique=False)
    op.create_table('vnp_regional_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('uptime_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('throughput_rps', sa.Integer(), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('provenance_hash', sa.String(), nullable=True),
    sa.Column('on_chain_anchor', sa.String(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regional_telemetry_region_score', 'vnp_regional_telemetry', ['region_code', 'trust_score', 'p99_latency_ms'], unique=False)
    op.create_table('vnp_route_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('p99_latency', sa.Float(), nullable=True),
    sa.Column('uptime_pct', sa.Float(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['vnp_route_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_snapshots_at', 'vnp_route_snapshots', ['snapshot_at'], unique=False)
    op.create_table('vnp_sdk_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['vnp_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('partition_key', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider_region', sa.String(length=50), nullable=False),
    sa.Column('sdk_region', sa.String(length=50), nullable=True),
    sa.Column('route_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('billable_units', sa.BigInteger(), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failover_count', sa.Integer(), nullable=False),
    sa.Column('preauth_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('final_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_alg', sa.String(length=20), nullable=False),
    sa.Column('signature_key_id', sa.String(length=100), nullable=False),
    sa.Column('signature_value', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_apis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['vnp_sdk_credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['vnp_route_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['vnp_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['vnp_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_snapshot_id'], ['vnp_route_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_usage_events_customer_time', 'vnp_usage_events', ['customer_id', 'occurred_at'], unique=False)
    op.create_index('idx_usage_events_project_time', 'vnp_usage_events', ['project_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_vnp_usage_events_partition_key'), 'vnp_usage_events', ['partition_key'], unique=False)
    op.create_table('vnp_settlement_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('usage_event_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.Enum('credit', 'debit', 'hold', 'release', 'refund', 'adjustment', 'slash', 'reward', name='ledger_entry_type_enum'), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.Enum('pending', 'posted', 'failed', 'reversed', name='settlement_state_enum'), nullable=False),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['vnp_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usage_event_id'], ['vnp_usage_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settlement_entries_customer_time', 'vnp_settlement_entries', ['customer_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_settlement_entries_customer_time', table_name='vnp_settlement_entries')
    op.drop_table('vnp_settlement_entries')
    op.drop_index(op.f('ix_vnp_usage_events_partition_key'), table_name='vnp_usage_events')
    op.drop_index('idx_usage_events_project_time', table_name='vnp_usage_events')
    op.drop_index('idx_usage_events_customer_time', table_name='vnp_usage_events')
    op.drop_table('vnp_usage_events')
    op.drop_table('vnp_sdk_credentials')
    op.drop_index('idx_route_snapshots_at', table_name='vnp_route_snapshots')
    op.drop_table('vnp_route_snapshots')
    op.drop_index('idx_regional_telemetry_region_score', table_name='vnp_regional_telemetry')
    op.drop_table('vnp_regional_telemetry')
    op.drop_index(op.f('ix_vnp_probe_events_partition_key'), table_name='vnp_probe_events')
    op.drop_index(op.f('ix_vnp_probe_events_measured_at'), table_name='vnp_probe_events')
    op.drop_index('idx_probe_events_api_region_time', table_name='vnp_probe_events')
    op.drop_table('vnp_probe_events')
    op.drop_index('idx_api_regions_lookup', table_name='vnp_api_regions', postgresql_where=sa.text('active = true'))
    op.drop_table('vnp_api_regions')
    op.drop_table('vnp_route_policies')
    op.drop_table('vnp_projects')
    op.drop_table('vnp_prepaid_balances')
    op.drop_table('vnp_attestations')
    op.drop_table('vnp_apis')
    op.drop_table('vnp_validators')
    op.drop_table('vnp_providers')
    op.drop_index('idx_incidents_state_opened', table_name='vnp_incidents')
    op.drop_table('vnp_incidents')
    op.drop_table('vnp_customers')
    op.drop_index(op.f('ix_vnp_claimed_apis_api_id'), table_name='vnp_claimed_apis')
    op.drop_table('vnp_claimed_apis')
    op.drop_index(op.f('ix_vnp_claim_requests_api_id'), table_name='vnp_claim_requests')
    op.drop_table('vnp_claim_requests')
    op.drop_index('idx_audit_logs_scope_time', table_name='vnp_audit_logs')
    op.drop_table('vnp_audit_logs')
    op.drop_table('vnp_alert_configs')
    for enum_name in (
        'tenant_type_enum',
        'incident_state_enum',
        'validator_state_enum',
        'api_status_enum',
        'attestation_state_enum',
        'ledger_entry_type_enum',
        'settlement_state_enum',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
